### ISSUE TITLE
How do we implement diagrams

### ISSUE THREAD

**Issue by DerMolly** [codimd/react-client#257] opened 2020-06-23 14:30 UTC
**Currently (1.6) supported**

- [x] [`sequence`](https://bramp.github.io/js-sequence-diagrams/) (#488)
- [x] [`flow`](https://flowchart.js.org/) (#502)
- [x] [`graphviz`](https://www.tonyballantyne.com/graphs.html) (#513)
- [x] [`mermaid`](https://mermaid-js.github.io/mermaid/#/) (#524)
- [x] [`abc`](https://abcnotation.com/learn) (#536)

**Requested**
- [x] [`markmap`](https://github.com/dundalek/markmap) (#571)
- [x] [`vega-lite`](https://github.com/vega/vega-lite) (#573)

How do we want to support those in the future. Apparently all of these use different underlying libraries. Maybe some of them can be merged?

If this issue get's closed there should be x new issues, where x is the number of libraries we need to add to the frontend. Ideally each issue describes what syntax the library shoudl support and if any legacy support is needed.

**Comment by mrdrogdrog** [comment] 2020-06-23 19:39
Okay let's see..
The main difference between these libs is the used syntax. I don't know if we can drop any of them. It could break existing code blocks.

The only one that could be problematic is graphviz, because https://github.com/mdaines/viz.js is deprecated and discontinued.

**Comment by ccoenen** [comment] 2020-06-23 21:35
A good long while ago we had the idea to split up the frontend js and make the various things more like plugins:

https://github.com/hackmdio/codimd/issues/1023

I stand by the original suggestion, but I think an extension should (not _must_) include an example on top of the three-ish things mentioned there.

**Comment by mrdrogdrog** [comment] 2020-06-23 21:43
The split up is one thing that we're already doing right now, (caused by the react component system). The question is: do we want to use all the diagramm types, code syntaxes and libs that were supported in 1.6?

**Comment by SuperSandro2000** [comment] 2020-06-23 21:51
I would implement the popular ones. I personally would care about mermaid the most.

**Comment by ccoenen** [comment] 2020-06-23 23:02
I think we should provide the pre-existing diagrams, to not break backwards-compatibility. I also think we should add them in the same way other plugins could work. We always had a ton of requests for various further extensions, and this would open it up to the broader community to some degree. Creating a plugin like this (especially when there are tons of examples) might be a nice way to start out development.

**Comment by SISheogorath** [comment] 2020-06-24 07:12
@mrdrogdrog for graphviz there is AFAIK a successor library that can be found in the forks graph of the library.

**Comment by ErikMichelson** [comment] 2020-06-24 09:45
This one looks more active: https://github.com/aduh95/viz.js

**Comment by mrdrogdrog** [comment] 2020-06-24 11:14
"a hack to put graphviz on the web"


![https://media.tenor.com/images/9bc18a6f8e59b3693150c78eb85dff22/tenor.gif](https://media.tenor.com/images/9bc18a6f8e59b3693150c78eb85dff22/tenor.gif)

**Comment by mrdrogdrog** [comment] 2020-06-24 14:23
I understand why this code is unmaintained. They took the graphviz cpp code and put it into webassembly

**Comment by DerMolly** [comment] 2020-09-16 08:39
Looking at [markmap](https://github.com/dundalek/markmap) seem to work on markdown texts. It seems to be used to render a mindmap of the toc as seen [here](https://markmap.js.org/repl). Do we still want that to be included?

**Comment by mrdrogdrog** [comment] 2020-09-16 10:24
Sure why not. Just pass the content from the code fence.

**Comment by mrdrogdrog** [comment] 2020-09-19 20:17
We implemented every diagram

![party](https://media1.giphy.com/media/4xZmzEuuQ8wnK/200.gif)

Can we close this issue now? It's main purpose was to hold a list of diagrams, that codimd 1.6 supports. For new suggestions we can open new issues.

**Closed** 2020-09-19 20:24 UTC
Labels: question
